### ISSUE TITLE
Wick panics when SQL component operation doesn't have `outputs`

### ISSUE THREAD

**Issue by shazaibn** [candlecorp/wick#332] opened 2023-06-27 14:20 UTC
**Describe the bug**
When I attempt to call an SQL operation via REST router that doesn't return any outputs, Wick panics and gives this error:

`2023-06-27T14:09:22 TRACE invocation{id=c13a9be2-f00f-4386-8e03-4cc89ea1649f target=wick://<null>/drop}: delivering packet flags=0 port="input" packet=Err(PacketError { msg: "component failed to produce output" })`

I have a REST route that calls a composite component that uses my SQL component operation. It is an update query that doesn't return any output.

**To Reproduce**
Invoke an SQL component operation through a composite component via REST route

**Expected behavior**
I expect Wick to make the update query call successfully and not have an issue with my component returning nothing.

**Actual behavior**
The error I provided above.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment] 2023-06-29 17:18
Closing this as fixed/could-not-reproduce. Turns out there was an encoding error that was being missed in the logs. #344 surfaces it better.

**Closed as completed by jsoverson** 2023-06-29 17:18 UTC
Labels: could-not-reproduce
